### ISSUE TITLE
Could not compile

### ISSUE THREAD

**Issue by solodyagin** [isemenkov/libpasyaml#1]
Could not compile libpasyaml_testproject with error:
pasyaml.pas(270,18) Error: Forward declaration not solved "CreateMapValue(AnsiString):TYamlFile.TOptionWriter;"

--
OS: Windows 11 [Version 10.0.22000.376]
Lazarus 2.3.0 (rev main-2_3-1026-ga57cf215d3) FPC 3.3.1 x86_64-win64-win32/win64
Free Pascal Compiler version 3.3.1-9820-ge091d263c8 [2021/12/30] for x86_64

**Comment by isemenkov** [comment]
Hello! Thank you for report, I will fix.

**Comment by RedCatN1** [comment]
It doesn't compile for me either with the same error
Lazarus 2.0.12 Win64 FPC 3.2

**Comment by isemenkov** [comment]
@solodyagin  @RedCatN1, fixed.

**Comment by RedCatN1** [comment]
Вы разговариваете по русски?Best regards,Andrey Devyatkin13:24, 16 января 2022 г., Ivan Semenkov ***@***.***>:
@solodyagin  @RedCatN1, fixed.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by isemenkov** [comment]
@RedCatN1 да, просто здесь как-то не принято ))

**Comment by RedCatN1** [comment]
Понимаю, поэтому и написал на английском сначала)) а так, пока самим компонентом не пользовался, но перевод заголовков бесценен) а кстати, компонент умеет сохранять, или только парсит? Просто я в своем проекте использовал Ваши заголовки, сохранение реализовывал вручную14:24, 16 января 2022 г., Ivan Semenkov ***@***.***>:
@RedCatN1 да, просто здесь как-то не принято ))

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by isemenkov** [comment]
Сама библиотека для которой транслированы заголовочные файлы умеет и читать и писать, но объектная обертка у меня - нет, но это можно не очень сложно делать напрямую. 
Я начал заниматься написанием новой обертки, которая сможет делать все что доступно в библиотеке, но это для меня хобби и занимаюсь я ним по факту наличия свободного времени, так что пока нет точных сроков завершения.

**Comment by RedCatN1** [comment]
Ну я пока не использую Вашу обёртку, т.к. нужно было распарсить yaml срочно, но заголовки очень помогли, а сохранение как-то через эмитер делается? Просто я не нашел доков на libyaml)14:57, 16 января 2022 г., Ivan Semenkov ***@***.***>:
Сама библиотека для которой транслированы заголовочные файлы умеет и читать и писать, но объектная обертка у меня - нет, но это можно не очень сложно делать напрямую.
Я начал заниматься написанием новой обертки, которая сможет делать все что доступно в библиотеке, но это для меня хобби и занимаюсь я ним по факту наличия свободного времени, так что пока нет точных сроков завершения.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by isemenkov** [comment]
> но заголовки очень помогли

Приятно что кому-то пригодилось ))
Я документации тоже не нашел, писал отчасти по наитию, отчасти посмотрев как в других библиотеках делают )

> а сохранение как-то через эмитер делается?

Да, через него.

**Comment by RedCatN1** [comment]
Ладно, нужно будет разобраться, а так спасибо за Ваш труд! Очень нужная штука получилась!15:34, 16 января 2022 г., Ivan Semenkov ***@***.***>:

но заголовки очень помогли

Приятно что кому-то пригодилось ))
Я документации тоже не нашел, писал отчасти по наитию, отчасти посмотрев как в бругих библиотеках делают )

а сохранение как-то через эмитер делается?

Да, через него.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by isemenkov** [comment]
Спасибо!
